FROM node:slim
WORKDIR /app/src/pacman
COPY src/main/node/package.json .
COPY src/main/node/package-lock.json .
COPY src/main/node/swagger .
WORKDIR /app/src/pacman/swagger
RUN npm install 
WORKDIR /app/src/pacman
RUN npm install
COPY src/main/node/ .
COPY src/test/resources/ .

CMD ["npm", "start"]
